version: 0.2
phases:
  install:
    runtime-versions: # https://docs.aws.amazon.com/ja_jp/codebuild/latest/userguide/build-spec-ref.html
      python: 3.7
    commands:
      - pipenv lock -r | pip install -r /dev/stdin -t src/vendor/
      - aws cloudformation package --template-file template.yml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file outputtemplate.yml
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml